name: Update README with Azure DevOps Stats

on:
  schedule:
    - cron: '0 18 * * *'  # Runs every day at 6 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Azure DevOps Stats
        env:
          AZURE_ORG: ${{ secrets.AZURE_ORG }}
          AZURE_PROJECT: ${{ secrets.AZURE_PROJECT }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          echo "Fetching work item stats from Azure DevOps..."
          response=$(curl -s -u :$AZURE_PAT "https://dev.azure.com/$AZURE_ORG/$AZURE_PROJECT/_apis/wit/workitems?api-version=6.0")
          echo "Response: $response"
          completed_items=$(echo $response | jq '[.value[] | select(.fields["System.State"] == "Closed")] | length')
          echo "Completed work items: $completed_items"
          echo "::set-output name=completed_items::$completed_items"

      - name: Count Commits
        run: |
          echo "Counting commits in the repository..."
          commit_count=$(git rev-list --count HEAD)
          echo "Total commits: $commit_count"
          echo "::set-output name=commit_count::$commit_count"

      - name: Update README
        run: |
          completed_items="${{ steps.fetch.outputs.completed_items }}"
          commit_count="${{ steps.count_commits.outputs.commit_count }}"
          echo "Updating README..."
          current_readme=$(cat README.md)
          new_readme=$(echo "$current_readme" | sed "s/- Completed Work Items: .*/- Completed Work Items: $completed_items/" | sed "s/- Total Commits: .*/- Total Commits: $commit_count/")
          echo "$new_readme" > README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update stats from Azure DevOps and commit count"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
